### PR TITLE
Dashboard fixes

### PR DESCRIPTION
**Pull request by sp116**
- fixed user details and displayed as paragraphs
- listed all student records on admin staff dashboard in collections
  with links for each student (TO DO: [admin] link to student dashboard)
- fixed card-actions to be consistent
- fixed column widths
- remove elements that were not needed

### CODE REVIEW

**Comment by sp116** [comment]
@tm112 @bd118 @AaronDunphyUniversity could one of you please review and merge to master :) or let me know if changes are required

**Comment by tm112** [comment]
I can do this a bit later when I am home :)

**Comment by tm112** [comment]
Actually just taken a look at all the files apart from the actual dashboard, they look fine. I wondered why there were so many changes then noticed that it is just the logout link being added. Will check the dashboard later

**Comment by ghost** [comment]
All looks good. I wondered why there were so many changes then noticed that it is just the logout link being added.

**Pull request merged**
